version: '3.8'
services:
  pepe:
    image: phptest:0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      MY_EN_VAR: Mi nombre es banannin
      DATABASE_NAME: pesetas
      DATABASE_URL: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: myroopass
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myroopass
    ports:
      - "3306:3306"
